apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-python
  template:
    metadata:
      labels:
        app: devops-python
    spec:
      containers:
      - name: python-app
        image: rushikeshkarande/devops-python-app:1.0
        ports:
        - containerPort: 8000
